### ISSUE TITLE
Sourcemaps are no longer correct, since v5.2.0, impossible to debug code.

### ISSUE THREAD

**Issue by WillooWisp** [AngularClass/angular-starter#1328]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Sourcemaps are no longer correct, since v5.2.0 (AOT support) when debugging TypeScript code, e.g. in browser (Chrome).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
1) Debugging TypeScript code works correctly with sourcemaps in version before v5.2.0 (02716cc21a3f53f62f12aad5ae22c20dbe421048), so try that, e.g. home.component.
2) Debugging in any version after (02716cc21a3f53f62f12aad5ae22c20dbe421048) does not work as expected. Breakpoints are hit in incorrect locations and cannot be set in others.

* **What is the expected behavior?**
Correct sourcemaps for debugging with TypeScript.

* **What is the motivation / use case for changing the behavior?**
It has worked before and must work in order to be productive.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Latest Chrome and Edge browsers. Compiling with npm run start:hmr.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by colinskow** [comment]
SourceMaps are disabled on purpose in production builds. They should work correctly on development builds. Let us know if that is not the case.

To enable source maps on your production build make this one change:
https://github.com/AngularClass/angular2-webpack-starter/pull/1299/files

**Comment by WillooWisp** [comment]
I am talking about development builds, that is why I wrote that I use npm run start:hmr. It is all really screwed up with debugging and breakpoints after AOT was introduced. Please help me find out what might have caused this since I am dependent on a working dev build with TypeScript debugging.

**Comment by d3viant0ne** [comment]
**AoT compilation has nothing to do with development builds.** 

**The addition of the yarn.lock file has no effect on a project unless you are using yarn to install.**

Given the differences in how yarn determines dependencies, I would either use npm or figure out the differences between what npm & yarn are installing.

I would start by version locking every one of your deps / devdeps and go from there, nothing you have mentioned above directly or indirectly effects dev builds or the debug workflow.

**Comment by WillooWisp** [comment]
I will try to be more clear, it has nothing to do with AOT itself, I am not even using it, but since the release that you have flagged as version v5.2.0, where you introduced AOT support in the setup, debugging does not work in Chrome and Edge for example. If you simply test debugging in the commit before v5.2.0 and then test again with v5.2.0 you will see that sourcemaps (or something else) is broken, since it is no longer possible to correctly debug and set breakpoints in the typescript code. Something, dependencies or configurations, that was changed in v5.2.0 caused this.

**Comment by WillooWisp** [comment]
And it has nothing to do with yarn or npm since I have tried both.

**Comment by WillooWisp** [comment]
I have now identified what is causing this. The change from module "commonjs" to "es2015" in compilerOptions (tsconfig.webpack.json) breaks the debugging support. I have now changed it back to commonjs and now it works again, what is the downside to this if any? Why the change to es2015 and why does that break debugging? Please update the config to work even for debugging scenarios.

**Comment by d3viant0ne** [comment]
What version of node are you running in your dev environment?

**Comment by WillooWisp** [comment]
Node version is: v6.9.1

**Comment by WillooWisp** [comment]
Okay I see, tree-shaking is nice, so a separate config file for now then I guess.

**Comment by kclay** [comment]
You can also use the `SourceMapDevToolPlugin` plugin
```js
const SourceMapDevToolPlugin= require('webpack/lib/SourceMapDevToolPlugin');

plugins[
...
new SourceMapDevToolPlugin()
...
]
```

This worked for me

**Comment by vaudy** [comment]
@WillooWisp  I had the same issue but I switch from 
    `devtool: 'cheap-module-source-map',`
to
    `devtool: 'eval-source-map',`

and it's working!

**Comment by colinskow** [comment]
It may slow down builds slightly, but perhaps we should change this temporarily in master until webpack/webpack#2145 is fixed?

**Comment by vaudy** [comment]
Colinskow sure at least it's working, I didn't try all the option, perhaps you could validate and take the fastest

**Comment by vaudy** [comment]
finally I still have issues on the initial load, breakpoint's not break but If I click on a button, it breaks. this is still unusable.

**Comment by vaudy** [comment]
I tried all options and `devtool: 'source-map'` is working, but slower

**Comment by bmayen** [comment]
Looks like this is fixed in Webpack@2.3.0

**Comment by colinskow** [comment]
This is fixed by upgrading to Webpack@2.3.2.

**Comment by Knaackee** [comment]
Still have this issue with webpack 2.3.3 has anyone a working example ?
